volumes:
  taski_pg_data:
  taski_static_value:

services:
  db:
    image: postgres:13
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - taski_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: warrior88888/taski_backend:latest
    restart: always
    env_file: .env
    volumes:
      - taski_static_value:/app/collected_static/
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: warrior88888/taski_frontend:latest
    restart: on-failure
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - taski_static_value:/frontend_static

  gateway:
    image: warrior88888/taski_gateway:latest
    restart: always
    ports:
      - "8000:80"
    volumes:
      - taski_static_value:/staticfiles/
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_completed_successfully